package com.peter.service.impl;

import com.alibaba.fastjson.JSONObject;
import com.peter.service.YamlService;
import com.peter.utils.ConfigTransferUtils;
import com.peter.utils.FileUtil;
import com.peter.utils.LinuxCmdUtils;
import com.peter.utils.YamlUtil;
import org.apache.commons.io.FileUtils;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Map;
import java.util.Properties;

/**
 * @author lcc
 * @date 2020/9/26 12:41
 */
@Service
public class YamlServiceImpl implements YamlService {


    @Override
    public Map<String, Object> read(String path) {
        Map<String, Object> res = YamlUtil.getYmlByFileName(path);
        return res;
    }

    @Override
    public boolean write(Map<String, Object> yaml,String path) {
        FileOutputStream fos=null;
        try {
            fos= new FileOutputStream(path);
            Properties properties = new Properties();
            for(String key:yaml.keySet()){
                properties.put(key,yaml.get(key));
            }
            properties.store(fos,"Generated By GrowingAi");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (fos!=null){
                try {
                    fos.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        ConfigTransferUtils.properties2Yaml(path);
//        boolean saveAsYaml = YamlUtil.saveAsYaml(yaml, path);
        return true;
    }
}
