package com.peter.bean;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.name
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.password
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.login_time
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.id
     *
     * @return the value of admins.id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.id
     *
     * @param id the value for admins.id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.name
     *
     * @return the value of admins.name
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.name
     *
     * @param name the value for admins.name
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.password
     *
     * @return the value of admins.password
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.password
     *
     * @param password the value for admins.password
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.login_time
     *
     * @return the value of admins.login_time
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.login_time
     *
     * @param loginTime the value for admins.login_time
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    @Override
    public String toString() {
        return "Admin{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                ", loginTime=" + loginTime +
                '}';
    }
}