package com.peter.bean;

import java.util.Date;

import org.apache.commons.lang3.time.DateFormatUtils;

import com.peter.utils.DateUtil;

public class Announce {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announces.id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announces.title
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announces.create_time
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announces.content
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announces.id
     *
     * @return the value of announces.id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announces.id
     *
     * @param id the value for announces.id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announces.title
     *
     * @return the value of announces.title
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announces.title
     *
     * @param title the value for announces.title
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announces.create_time
     *
     * @return the value of announces.create_time
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announces.create_time
     *
     * @param createTime the value for announces.create_time
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announces.content
     *
     * @return the value of announces.content
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announces.content
     *
     * @param content the value for announces.content
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "Announce [id=" + id + ", title=" + title + ", createTime=" + DateFormatUtils.format(createTime, DateUtil.formatDateString) + ", content=" + content + "]";
	}
    
}