package com.peter.bean;

public class FileType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_types.id
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_types.name
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_types.id
     *
     * @return the value of file_types.id
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_types.id
     *
     * @param id the value for file_types.id
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_types.name
     *
     * @return the value of file_types.name
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_types.name
     *
     * @param name the value for file_types.name
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}