package com.peter.bean;

/**
 * @author lcc
 * @date 2020/5/17 13:34
 */
public class Model {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_models.id
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    protected Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_models.name
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    protected String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_models.json
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    protected String json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_models.id
     *
     * @return the value of sys_models.id
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_models.id
     *
     * @param id the value for sys_models.id
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_models.name
     *
     * @return the value of sys_models.name
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_models.name
     *
     * @param name the value for sys_models.name
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_models.json
     *
     * @return the value of sys_models.json
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_models.json
     *
     * @param json the value for sys_models.json
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    public void setJson(String json) {
        this.json = json == null ? null : json.trim();
    }

}
