package com.peter.bean;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.user_id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.score
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.id
     *
     * @return the value of scores.id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.id
     *
     * @param id the value for scores.id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.user_id
     *
     * @return the value of scores.user_id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.user_id
     *
     * @param userId the value for scores.user_id
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.score
     *
     * @return the value of scores.score
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.score
     *
     * @param score the value for scores.score
     *
     * @mbggenerated Sat Oct 19 21:20:29 CST 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

	@Override
	public String toString() {
		return "Score [id=" + id + ", userId=" + userId + ", score=" + score + "]";
	}
    
}