package com.peter.bean;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.project_id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.score
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    private Double score;

    private Project project;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.id
     *
     * @return the value of scores.id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.id
     *
     * @param id the value for scores.id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.project_id
     *
     * @return the value of scores.project_id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.project_id
     *
     * @param projectId the value for scores.project_id
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.score
     *
     * @return the value of scores.score
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.score
     *
     * @param score the value for scores.score
     *
     * @mbggenerated Sat Nov 16 15:53:31 CST 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @Override
    public String toString() {
        return "Score{" +
                "id=" + id +
                ", projectId=" + projectId +
                ", score=" + score +
                '}';
    }
}