package com.peter.bean;

import java.util.Objects;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column types.id
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column types.name
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column types.id
     *
     * @return the value of types.id
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column types.id
     *
     * @param id the value for types.id
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column types.name
     *
     * @return the value of types.name
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column types.name
     *
     * @param name the value for types.name
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Type)) return false;
        Type type = (Type) o;
        return Objects.equals(getId(), type.getId()) &&
                getName().equals(type.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getName());
    }

    @Override
    public String toString() {
        return "Type{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}