package com.peter.bean;

public class UserModel extends Model{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_models.user_id
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    private Integer userId;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_models.user_id
     *
     * @return the value of user_models.user_id
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_models.user_id
     *
     * @param userId the value for user_models.user_id
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "UserModel{" +
                "userId=" + userId +
                ", id=" + id +
                ", name='" + name + '\'' +
                ", json='" + json + '\'' +
                '}';
    }
}