package com.peter.mapper;

import com.peter.bean.Dataset;
import com.peter.bean.DatasetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DatasetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int countByExample(DatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int deleteByExample(DatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int insert(Dataset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int insertSelective(Dataset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    List<Dataset> selectByExample(DatasetExample example);

    List<Dataset> selectSimpleByExample(DatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    Dataset selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") Dataset record, @Param("example") DatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int updateByExample(@Param("record") Dataset record, @Param("example") DatasetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int updateByPrimaryKeySelective(Dataset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datasets
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int updateByPrimaryKey(Dataset record);
}