package com.peter.mapper;

import com.peter.bean.FileType;
import com.peter.bean.FileTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int countByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int deleteByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int insert(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int insertSelective(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    List<FileType> selectByExample(FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    FileType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") FileType record, @Param("example") FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int updateByExample(@Param("record") FileType record, @Param("example") FileTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int updateByPrimaryKeySelective(FileType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_types
     *
     * @mbggenerated Sun Aug 09 11:51:04 CST 2020
     */
    int updateByPrimaryKey(FileType record);
}