package com.peter.mapper;

import com.peter.bean.SysModel;
import com.peter.bean.SysModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int countByExample(SysModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int deleteByExample(SysModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int insert(SysModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int insertSelective(SysModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    List<SysModel> selectByExample(SysModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    SysModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysModel record, @Param("example") SysModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int updateByExample(@Param("record") SysModel record, @Param("example") SysModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int updateByPrimaryKeySelective(SysModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int updateByPrimaryKey(SysModel record);
}