package com.peter.mapper;

import com.peter.bean.Type;
import com.peter.bean.TypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int countByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int deleteByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    List<Type> selectByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    Type selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") Type record, @Param("example") TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int updateByExample(@Param("record") Type record, @Param("example") TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table types
     *
     * @mbggenerated Wed Feb 19 18:54:33 CST 2020
     */
    int updateByPrimaryKey(Type record);
}