package com.peter.mapper;

import com.peter.bean.UserModel;
import com.peter.bean.UserModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int countByExample(UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int deleteByExample(UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    List<UserModel> selectByExample(UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    UserModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserModel record, @Param("example") UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int updateByExample(@Param("record") UserModel record, @Param("example") UserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_models
     *
     * @mbggenerated Sat May 23 14:03:56 CST 2020
     */
    int updateByPrimaryKey(UserModel record);
}